const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('js/app.js','utf8'),css=fs.readFileSync('css/app.css','utf8'),tokens=fs.readFileSync('css/tokens.css','utf8');
assert(html.includes('data-page="settings"'));
assert(html.includes('id="settingsButton"'));
assert(!html.includes('id="versionChip"'));
assert(app.includes("appearance:'system'")||fs.readFileSync('js/core/state.js','utf8').includes("appearance:'system'"));
assert(app.includes('function applyAppearance'));
assert(app.includes('data-appearance'));
assert(app.includes('data-accent'));
assert(tokens.includes('html[data-theme="light"]'));
assert(tokens.includes('html[data-accent="blue"]'));
assert(tokens.includes('html[data-accent="green"]'));
assert(tokens.includes('html[data-accent="purple"]'));
assert(app.includes('function calendarMonthHtml'));
assert(app.includes('data-calendar-view="month"'));
assert(app.includes('data-calendar-view="agenda"'));
assert(app.includes('data-calendar-date'));
assert(css.includes('.calendar-grid{'));
assert(css.includes('.settings-section{'));
assert(css.includes('.accent-swatches{'));
assert(app.includes('data-go="settings"'));
console.log('appearance-calendar.test.js OK');
