const assert=require('assert'),fs=require('fs'),vm=require('vm');
const release=JSON.parse(fs.readFileSync('release.json','utf8'));
const ctx={globalThis:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('config/app-config.js','utf8'),ctx);
const C=ctx.globalThis.GMB_CONFIG;
assert.strictEqual(C.version,'0.7.0');assert.strictEqual(C.schemaVersion,3);assert.strictEqual(release.version,C.version);assert.strictEqual(release.autofetch.enabled,true);assert.strictEqual(release.autofetch.calendar,true);assert.strictEqual(release.autofetch.failureAlerts,'github-issue');
const sw=fs.readFileSync('sw.js','utf8'),html=fs.readFileSync('index.html','utf8');
assert(sw.includes("const VERSION='0.7.0'"));assert(sw.includes('./release.json'));assert(sw.includes('./js/system-health.js'));assert(sw.includes('./js/domain/review.js'));assert(sw.includes('./data/school-calendar-meta.json'));
assert(html.includes('system-health.js?v=0.7.0'));assert(html.includes('review.js?v=0.7.0'));assert(html.includes('data-page="system"'));assert(html.includes('data-page="review"'));
const auto=fs.readFileSync('.github/workflows/autofetch.yml','utf8'),cal=fs.readFileSync('.github/workflows/calendar-autofetch.yml','utf8'),pages=fs.readFileSync('.github/workflows/pages.yml','utf8');
assert(auto.includes('schedule:'));assert(auto.includes('scholarship_autofetch.py'));assert(auto.includes('autofetch.py --repo . --apply'));assert(auto.includes('Public Data AutoFetch failed'));
assert(cal.includes('Basketball Goal Manager THU Calendar AutoFetch'));assert(cal.includes('calendar_autofetch.py --repo .'));assert(cal.includes('THU Calendar AutoFetch failed'));
assert(pages.includes('Basketball Goal Manager THU Calendar AutoFetch'));assert(pages.includes('release-preflight.sh'));
console.log('release-contract.test.js OK');
