const assert=require('assert');
const H=require('../js/system-health.js');
const now=Date.parse('2026-10-08T00:00:00Z');
let x=H.activity({meta:{updatedAt:'2026-10-07T20:00:00Z',totalSources:5,healthySources:5,needsReview:2},events:[{id:'a'}]},{ok:true},now);
assert.strictEqual(x.status,'fresh');assert.strictEqual(x.count,1);assert.strictEqual(x.sourceText,'5/5 來源正常');
x=H.activity({meta:{updatedAt:'2026-10-01T08:00:00Z'},events:[]},{ok:true},now);assert.strictEqual(x.status,'stale');
x=H.activity({}, {ok:false,error:'HTTP 500'}, now);assert.strictEqual(x.status,'error');assert.strictEqual(x.count,null);
const s=H.scholarship({meta:{updatedAt:'2026-10-07T20:00:00Z',categories:5,healthyCategories:4,eligibilityDetail:{detailVerified:100,detailUnverified:25}},scholarships:[{id:'s'}]},{ok:true},now);
assert.strictEqual(s.sourceText,'4/5 類別正常');assert.strictEqual(s.verified,100);assert.strictEqual(s.unverified,25);
let c=H.calendar([{date:'2026-09-14'}],{ok:true},{academicYear:115,checkedAt:'2026-10-07T20:00:00Z',sourceAnnouncementUrl:'https://example.test'},now);
assert.strictEqual(c.status,'ready');assert.strictEqual(c.label,'已同步');assert.strictEqual(c.count,1);
c=H.calendar([{date:'2026-09-14'}],{ok:true},{academicYear:115,checkedAt:'2026-10-01T00:00:00Z'},now);assert.strictEqual(c.status,'stale');
c=H.calendar([{date:'2026-09-14'}],{ok:true},{academicYear:115},now);assert.strictEqual(c.status,'unknown');
assert.strictEqual(H.publicSummary({activity:x,scholarship:s,calendar:H.calendar([{date:'x'}],{ok:false,error:'bad'},{},now)}).status,'error');
let v=H.versionSummary({pageVersion:'0.7.0',workerVersion:'0.7.0',releaseVersion:'0.7.0',controlled:true,online:true});assert.strictEqual(v.status,'good');assert.strictEqual(v.coherent,true);
v=H.versionSummary({pageVersion:'0.7.0',workerVersion:'0.7.0',releaseVersion:'0.8.0',controlled:true,online:true});assert.strictEqual(v.status,'update');assert.strictEqual(v.updateAvailable,true);
v=H.versionSummary({pageVersion:'0.7.0',workerVersion:'0.6.1',releaseVersion:'0.7.0',controlled:true,online:true});assert.strictEqual(v.status,'mismatch');
console.log('system-health.test.js OK');
